# Generated by Django 5.2.8 on 2025-11-24 13:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandInReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('finder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('finder_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('IDS', 'IDs & Cards'), ('KEYS', 'Keys'), ('BOOKS', 'Books & Stationery'), ('BAGS', 'Bags & Wallets'), ('TUMBLERS', 'Tumblers/Bottles'), ('OTHERS', 'Others')], default='OTHERS', max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=30)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('location_found', models.CharField(max_length=255)),
                ('is_received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student/Crew')], default='STUDENT', max_length=10)),
                ('student_id', models.CharField(blank=True, help_text='Enter your 7-digit ID number.', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', message='Student ID must be exactly 7 digits.')])),
                ('program_year', models.CharField(blank=True, choices=[('1st Year', 'First Year'), ('2nd Year', 'Second Year'), ('3rd Year', 'Third Year'), ('4th Year', 'Fourth Year'), ('5th Year', 'Fifth Year'), ('6th Year', 'Sixth Year')], max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(max_length=50)),
                ('target_object_id', models.CharField(max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('IDS', 'IDs & Cards'), ('KEYS', 'Keys'), ('BOOKS', 'Books & Stationery'), ('BAGS', 'Bags & Wallets'), ('TUMBLERS', 'Tumblers/Bottles'), ('OTHERS', 'Others')], max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=30)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('date_found', models.DateField()),
                ('location_found', models.CharField(max_length=255)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('DONATED', 'Donated/Disposed')], default='AVAILABLE', max_length=20)),
                ('registered_by', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hand_in_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.handinreport')),
            ],
        ),
        migrations.CreateModel(
            name='LostItemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('IDS', 'IDs & Cards'), ('KEYS', 'Keys'), ('BOOKS', 'Books & Stationery'), ('BAGS', 'Bags & Wallets'), ('TUMBLERS', 'Tumblers/Bottles'), ('OTHERS', 'Others')], max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=30)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='lost_tickets/')),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=255)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching'), ('MATCH_FOUND', 'Potential Match Found'), ('CLOSED', 'Closed/Found')], default='SEARCHING', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_ownership', models.TextField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='claims_evidence/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Item Picked Up')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.founditem')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lostitemticket')),
            ],
        ),
    ]
