# Generated by Django 5.2.8 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lostitemticket_matched_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitemticket',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching'), ('MATCH_FOUND', 'Potential Match Found'), ('CLAIM_PENDING', 'Claim Verification in Progress'), ('CLOSED', 'Closed/Found')], default='SEARCHING', max_length=20),
        ),
    ]
